---
- hosts: k8smaster
  tasks:
  - name: Timestamp
    debug: msg="{{ lookup('pipe','date +%H:%M:%S') }}"

  - name: Do pre-flight checks and initialize cluster
    shell: kubeadm init \
              --ignore-preflight-errors all \
              --service-dns-domain jody.org \
              --pod-network-cidr=192.178.0.0/16

  - name: Timestamp
    debug: msg="{{ lookup('pipe','date +%H:%M:%S') }}"

  - name: Create .kube config
    shell: |
      rm -rf $HOME/.kube
      mkdir -p $HOME/.kube
      cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      chown $(id -u):$(id -g) $HOME/.kube/config
    warn: false

  - name: Install Weave Net
    shell: kubectl apply -f \
             "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

  - name: Install k8s dashboard
    shell: |
      kubectl apply -f \
             https\://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
      kubectl proxy

  - name: Install Weave Scope
    shell: |
      kubectl apply -f "https://cloud.weave.works/k8s/scope.yaml?k8s-version=$(kubectl version | base64 | tr -d '\n')"
      kubectl port-forward -n weave "$(kubectl get -n weave pod --selector=weave-scope-component=app -o jsonpath='{.items..metadata.name}')" 4040

  - name: Remove taint on Master
    shell: kubectl taint nodes --all node-role.kubernetes.io/master-
